### PR TITLE
adding negative number check and solving format

### LINKED ISSUE #11: User should be warned when $position(arg[0], arg[1]) returns a value outside of the screen
When a user tries to print a string with 40 or more characters from the middle of the screen using:
``` 
  loadn r1, $position(eval((40-int(defs["var_len"]))//2),0) 
```
``` defs["var_len"] ``` will be greater than 40, when this happens the first argument of ``` $position(arg[0], arg[1])``` is a negative value, and the screen can only print from 0 to 1199, so the user should be warned when ``` $position(arg[0], arg[1])``` returns a value outside this range.

_Originally posted by @cirillom in https://github.com/lucasgpulcinelli/ICMC-assembly-preprocessor/issues/10#issuecomment-1255039116_

### PR DESCRIPTION
**Pull request by lucasgpulcinelli**
partially fixes #11 (and it will be the only work to be done for it)

### CODE REVIEW

**Review by cirillom — COMMENTED** [review]
Does this also warns the user which line the problem appears? Is this even possible?

**Comment by lucasgpulcinelli** [comment]
Yes! At line 190 of the new file (in except block in preprocess()) you can see a ValueError exception message and the line of the error. You can test the preprocessor by using (at the root of the repo) `python src/preprocessor.py res/charmap.json examples/hello_world.asm /tmp/out.asm`. If you change, for instance, the postion macro at line 12 of examples/preprocessor.py to include negative numbers, a nice error message is printed and the program fails.

**Comment by lucasgpulcinelli** [comment]
@cirillom ping to merge the pull request if possible, or show more work to be done

**Review by cirillom — APPROVED** [review]
Excellent solution, code is really nice and concise, congrats

**Pull request merged**
